import { render } from "./visualizer.js";
import { ready, run, trace } from "./runner.js";
import { pythonToHtml } from "./highlight.js";

// The problem list is data: problems/index.json, generated by tools/record.py.
/** Index of the checkpoint that blocks advancing past `index`, or null. */
export function nextBlockingCheckpoint(checkpoints, answered, index) {
  for (let i = 0; i < checkpoints.length; i++) {
    if (checkpoints[i].afterStep === index && !answered.has(i)) return i;
  }
  return null;
}

if (document.getElementById("viz")) {

const $ = (id) => document.getElementById(id);
let problem = null, index = 0, answered = new Set(), hintsUsed = 0, code = "";
// Solved means every test passed at least once — it is never unset by a
// later failing run, so experimenting after solving costs nothing.
let solved = false;
// Non-null while showing the learner's own traced run instead of the reference.
let mine = null;

const storageKey = () => `codeteach:${problem.id}`;

const COLLAPSED_KEY = "codeteach:collapsed";

function readCollapsed() {
  try { return JSON.parse(localStorage.getItem(COLLAPSED_KEY) ?? "[]"); }
  catch { return []; }
}

/** Progress for one problem, readable without loading it — the sidebar needs
 *  every problem's state before any of them is open. */
function progressOf(id) {
  try { return JSON.parse(localStorage.getItem(`codeteach:${id}`) ?? "{}"); }
  catch { return {}; }
}

function save() {
  localStorage.setItem(storageKey(),
    JSON.stringify({ answered: [...answered], hintsUsed, solved,
                     code: $("editor").value }));
}

function load() {
  try {
    const raw = JSON.parse(localStorage.getItem(storageKey()) ?? "{}");
    answered = new Set(raw.answered ?? []);
    hintsUsed = raw.hintsUsed ?? 0;
    code = raw.code ?? "";
    solved = raw.solved === true;
  } catch { answered = new Set(); hintsUsed = 0; code = ""; solved = false; }
}

async function loadProblem(id) {
  try {
    const res = await fetch(`problems/${id}.json`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    problem = await res.json();
  } catch (err) {
    $("caption").textContent =
      `Could not load the problem "${id}" (${err.message}). Serve this app over http:// and reload the page.`;
    return;
  }
  index = 0;
  mine = null;
  load();
  $("title").textContent = problem.title;
  $("statement").innerHTML = problem.statement
    .split("\n\n").map(p => `<p>${inline(p)}</p>`).join("");
  $("examples").innerHTML = problem.examples
    .map(e => `<div>Input: ${e.input}<br>Output: ${e.output}</div>`).join("");
  $("editor").value = code || `${problem.signature}\n${INDENT}`;
  drawGutter();
  paint();
  $("scrub").max = String(problem.steps.length - 1);
  $("results").replaceChildren();
  renderHints();
  draw();
}

// ponytail: bold + inline code only. Problem statements are ours, not user input.
const inline = (s) => s
  .replace(/&/g, "&amp;").replace(/</g, "&lt;")
  .replace(/`([^`]+)`/g, "<code>$1</code>")
  .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");

function renderHints() {
  $("hints").innerHTML = problem.hints.slice(0, hintsUsed)
    .map(h => `<p>${inline(h)}</p>`).join("");
  $("hint-count").textContent = `${hintsUsed} of ${problem.hints.length} hints used`;
  $("hint-btn").disabled = hintsUsed >= problem.hints.length;
}

function draw() {
  // `mine` holds the learner's own traced run. The reference walkthrough in
  // problem.steps is never overwritten — switching back is just dropping it.
  const steps = mine ?? problem.steps;
  const checkpoints = mine ? [] : problem.checkpoints;

  render($("viz"), steps[index], problem.view);
  $("caption").textContent = steps[index].caption ?? "";
  $("step-count").textContent = `${index + 1} / ${steps.length}`;
  $("scrub").max = String(steps.length - 1);
  $("scrub").value = String(index);
  $("mine-bar").hidden = !mine;

  const blocked = nextBlockingCheckpoint(checkpoints, answered, index);
  const atEnd = index >= steps.length - 1;
  $("next").disabled = blocked !== null || atEnd;
  $("last").disabled = blocked !== null || atEnd;
  $("scrub").disabled = blocked !== null;
  $("prev").disabled = index === 0;
  $("first").disabled = index === 0;

  if (blocked === null) { $("checkpoint").hidden = true; return; }
  const cp = problem.checkpoints[blocked];
  $("checkpoint").hidden = false;
  $("cp-question").textContent = cp.question;
  $("cp-feedback").textContent = "";
  $("cp-options").replaceChildren(...cp.options.map(opt => {
    const b = document.createElement("button");
    b.className = "ghost";
    b.textContent = opt;
    b.onclick = () => {
      if (opt === cp.answer) {
        answered.add(blocked);
        save();
        draw();
        $("checkpoint").hidden = false;
        $("cp-question").textContent = "Right.";
        $("cp-options").replaceChildren();
        $("cp-feedback").textContent = cp.why;
      } else {
        $("cp-feedback").textContent = `Not quite. ${cp.why}`;
      }
    };
    return b;
  }));
}

function go(i) {
  const steps = mine ?? problem.steps;
  const checkpoints = mine ? [] : problem.checkpoints;
  const target = Math.max(0, Math.min(steps.length - 1, i));
  // Never step past an unanswered gate.
  for (let k = index; k < target; k++) {
    if (nextBlockingCheckpoint(checkpoints, answered, k) !== null) {
      index = k; draw(); return;
    }
  }
  index = target;
  draw();
}

function showMine(steps) {
  mine = steps;
  index = 0;
  draw();
}

$("next").onclick = () => go(index + 1);
$("prev").onclick = () => go(index - 1);
$("first").onclick = () => go(0);
$("last").onclick = () => go((mine ?? problem.steps).length - 1);
$("scrub").oninput = (e) => go(Number(e.target.value));
$("hint-btn").onclick = () => { hintsUsed++; save(); renderHints(); };
$("editor").oninput = () => { save(); drawGutter(); paint(); };
$("editor").onscroll = () => {
  $("gutter").scrollTop = $("editor").scrollTop;
  $("highlight").scrollTop = $("editor").scrollTop;
  $("highlight").scrollLeft = $("editor").scrollLeft;
};

/** Repaints the highlight layer sitting behind the transparent textarea. */
function paint() {
  $("highlight").firstElementChild.innerHTML = pythonToHtml($("editor").value);
}

function drawGutter() {
  const lines = $("editor").value.split("\n").length;
  $("gutter").textContent = Array.from({ length: lines }, (_, i) => i + 1).join("\n");
}

// ponytail: Tab and auto-indent only — the two things a plain textarea gets
// wrong for Python. No syntax highlighting: that needs a real editor library,
// and this stays a zero-dependency static page. Swap in CodeMirror if you
// ever want colour, not before.
const INDENT = "    ";

$("editor").onkeydown = (e) => {
  const ed = e.target;
  const { selectionStart: a, selectionEnd: b, value: v } = ed;

  const replace = (text, caret) => {
    ed.setRangeText(text, a, b, "end");
    if (caret !== undefined) ed.selectionStart = ed.selectionEnd = caret;
    ed.dispatchEvent(new Event("input"));
  };

  if (e.key === "Tab") {
    e.preventDefault();
    if (e.shiftKey) {
      // Dedent the current line by up to one indent level.
      const lineStart = v.lastIndexOf("\n", a - 1) + 1;
      const lead = v.slice(lineStart, lineStart + INDENT.length);
      const cut = lead.startsWith(INDENT) ? INDENT.length : lead.search(/[^ ]|$/);
      if (cut) {
        ed.setRangeText("", lineStart, lineStart + cut, "preserve");
        ed.dispatchEvent(new Event("input"));
      }
      return;
    }
    replace(INDENT);
    return;
  }

  if (e.key === "Enter") {
    e.preventDefault();
    const lineStart = v.lastIndexOf("\n", a - 1) + 1;
    const line = v.slice(lineStart, a);
    let indent = line.match(/^ */)[0];
    if (line.trimEnd().endsWith(":")) indent += INDENT;
    replace("\n" + indent);
  }
};

$("mine-back").onclick = () => { mine = null; index = 0; draw(); };

$("viz-mine").onclick = async () => {
  const btn = $("viz-mine");
  const ran = problem;              // a trace belongs to the problem it came from
  const src = $("editor").value;
  const stale = () => problem !== ran;
  const args = ran.tests[0].args;   // the first case is the one the examples show
  btn.disabled = true;
  $("results").textContent = "Tracing your code…";
  try {
    await ready((msg) => { if (!stale()) $("results").textContent = msg; });
    const out = await trace(src, ran.func, args);
    if (stale()) return;

    if (!out.steps.length) {
      $("results").textContent = out.error
        ? `Could not trace your code: ${out.error}`
        : `Your ${ran.func} ran without any state to watch — no loop variables changed.`;
      return;
    }
    showMine(out.steps);

    const notes = [`Traced your run on ${JSON.stringify(args)} — ${out.steps.length} frames.`];
    if (out.error) notes.push(`It stopped early: ${out.error}`);
    else notes.push(`It returned ${JSON.stringify(out.result)}.`);
    if (out.truncated) notes.push("Only the first 400 frames were captured.");
    $("results").textContent = notes.join(" ");
  } catch (err) {
    if (!stale()) $("results").textContent = `${err.message} — press the button again.`;
  } finally {
    btn.disabled = false;
  }
};

$("run").onclick = async () => {
  const btn = $("run");
  const ran = problem; // results belong to this problem only
  const src = $("editor").value;
  const stale = () => problem !== ran;
  btn.disabled = true;
  $("results").textContent = "Starting Python…";
  try {
    await ready((msg) => { if (!stale()) $("results").textContent = msg; });
    const results = await run(src, ran.func, ran.tests);
    if (stale()) return;
    $("results").replaceChildren(...results.map(r => {
      const div = document.createElement("div");
      div.className = "result " + (r.pass ? "pass" : "fail");
      const head = r.pass ? "PASS" : "FAIL";
      div.innerHTML = `<strong>${head}</strong> ${escapeHtml(JSON.stringify(r.args))}`;
      const pre = document.createElement("pre");
      pre.textContent = r.error
        ? r.error
        : `expected ${JSON.stringify(r.expect)}\ngot      ${JSON.stringify(r.actual)}`;
      if (!r.pass) div.appendChild(pre);
      return div;
    }));

    if (results.length && results.every(r => r.pass) && !solved) {
      solved = true;
      save();
      markSolved(ran.id);
    }
  } catch (err) {
    if (!stale()) $("results").textContent = `${err.message} — check your connection and press Run again.`;
  } finally {
    btn.disabled = false;
  }
};

const escapeHtml = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;");

/** Reflects a freshly solved problem in the sidebar without rebuilding it,
 *  so the tick and its pattern's count appear the moment the tests pass. */
function markSolved(id) {
  const btn = $("problem-list").querySelector(`button[data-id="${id}"]`);
  if (!btn || btn.classList.contains("solved")) return;
  btn.classList.add("solved");

  const pattern = btn.dataset.pattern;
  const siblings = [...$("problem-list").querySelectorAll(`button[data-pattern="${pattern}"]`)];
  const done = siblings.filter(b => b.classList.contains("solved")).length;
  const count = $("problem-list").querySelector(`.count[data-pattern="${pattern}"]`);
  if (count) {
    count.textContent = `${done}/${siblings.length}`;
    count.classList.toggle("all", done === siblings.length);
  }
  updateTotal();
}

function updateTotal() {
  const all = [...$("problem-list").querySelectorAll("button[data-id]")];
  const done = all.filter(b => b.classList.contains("solved")).length;
  $("total-progress").textContent = `${done} of ${all.length} solved`;
  $("total-bar").style.setProperty("--pct", all.length ? `${(done / all.length) * 100}%` : "0%");
}

function select(id) {
  $("picker").value = id;
  for (const b of $("problem-list").querySelectorAll("button")) {
    b.setAttribute("aria-current", String(b.dataset.id === id));
  }
  loadProblem(id);
}

/** Builds the sidebar from problems/index.json: the curriculum in teaching
 *  order, each pattern holding its problems. Patterns with nothing in them yet
 *  are shown but not clickable — they say what is coming, they do not pretend
 *  to be ready. */
async function buildSidebar() {
  let index;
  try {
    const res = await fetch("problems/index.json");
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    index = await res.json();
  } catch (err) {
    $("problem-list").textContent =
      `Could not load the problem list (${err.message}).`;
    return;
  }

  const ids = [];
  const nodes = [];

  const collapsed = new Set(readCollapsed());

  for (const { name, problems } of index.patterns) {
    const group = document.createElement("li");
    group.className = "group" + (problems.length ? "" : " empty");

    const done = problems.filter(p => progressOf(p.id).solved).length;
    const count = document.createElement("span");
    count.className = "count" + (problems.length && done === problems.length ? " all" : "");
    count.dataset.pattern = name;
    count.textContent = problems.length ? `${done}/${problems.length}` : "soon";

    // A pattern with nothing in it has nothing to expand, so it stays a plain
    // row rather than a disclosure that opens onto emptiness.
    if (!problems.length) {
      const head = document.createElement("p");
      head.className = "group-head";
      head.append(name, count);
      group.appendChild(head);
      nodes.push(group);
      continue;
    }

    const details = document.createElement("details");
    details.dataset.pattern = name;
    details.open = !collapsed.has(name);
    // The toggle listener is attached after insertion, below: setting `open`
    // here fires a toggle of its own, and recording that would persist a
    // collapse the reader never asked for.

    const summary = document.createElement("summary");
    summary.className = "group-head";
    summary.innerHTML = '<span class="chevron" aria-hidden="true"></span>';
    summary.append(name, count);
    details.appendChild(summary);

    const ul = document.createElement("ul");
    for (const { id, title } of problems) {
      ids.push(id);
      const li = document.createElement("li");
      const b = document.createElement("button");
      b.type = "button";
      b.dataset.id = id;
      b.innerHTML = '<span class="dot"></span>';
      // The sidebar shows the short name; the full title heads the problem.
      b.append(title.split("—")[0].trim());
      if (progressOf(id).solved) b.classList.add("solved");
      b.dataset.pattern = name;
      b.onclick = () => select(id);
      li.appendChild(b);
      ul.appendChild(li);
    }
    details.appendChild(ul);
    group.appendChild(details);
    nodes.push(group);
  }

  $("problem-list").replaceChildren(...nodes);

  // Setting `open` above queues a toggle event per group. Those land before
  // this timeout runs, so only a real click reaches the listener — otherwise
  // building the sidebar would persist a collapse nobody asked for.
  setTimeout(() => {
    for (const d of $("problem-list").querySelectorAll("details")) {
      d.addEventListener("toggle", () => {
        const now = new Set(readCollapsed());
        d.open ? now.delete(d.dataset.pattern) : now.add(d.dataset.pattern);
        localStorage.setItem(COLLAPSED_KEY, JSON.stringify([...now]));
      });
    }
  }, 0);

  // The select stays the source of truth so every path agrees on what is open.
  $("picker").replaceChildren(...ids.map(id => {
    const o = document.createElement("option");
    o.value = id;
    o.textContent = id;
    return o;
  }));
  $("picker").onchange = (e) => select(e.target.value);

  updateTotal();
  if (ids.length) select(ids[0]);
}

buildSidebar();

}
